#!/usr/bin/env python3
"""Generate explicit singular inflections for selected TERYT city names.

All one-token official cities get a canonical nominative entry in the source
layer. Full singular inflection is generated for:
  * the top N cities by wordfreq Polish frequency;
  * explicit project-priority cities in a reviewed TSV.

Only forms generated by Morfeusz 2 / SGJP are emitted.
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

CASES = ("nom", "gen", "dat", "acc", "inst", "loc", "voc")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cities", type=Path, required=True)
    ap.add_argument("--priorities", type=Path, required=True)
    ap.add_argument("--top-n", type=int, default=300)
    ap.add_argument("--out-tsv", type=Path, required=True)
    ap.add_argument("--out-report", type=Path, required=True)
    return ap.parse_args()


def load_tsv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def case_from_tag(tag: str) -> set[str]:
    parts = tag.split(":")
    if len(parts) < 3 or parts[0] != "subst" or parts[1] != "sg":
        return set()
    return {c for c in parts[2].split(".") if c in CASES}


def main() -> int:
    args = parse_args()
    cities = load_tsv(args.cities)
    priorities = {row["name"].strip().lower() for row in load_tsv(args.priorities) if row.get("name", "").strip()}
    if not cities:
        raise SystemExit("No cities supplied")

    from wordfreq import zipf_frequency
    ranked = sorted(
        cities,
        key=lambda row: (-float(zipf_frequency(row["name"], "pl")), row["name"].lower()),
    )

    selected = {row["name"].lower() for row in ranked[:args.top_n]}
    selected |= priorities

    import morfeusz2
    from polish_inflection import (
        MIANOWNIK,
        DOPEŁNIACZ,
        CELOWNIK,
        BIERNIK,
        NARZĘDNIK,
        MIEJSCOWNIK,
        WOŁACZ,
        POJEDYNCZA,
        odmien_warianty,
        podaj,
    )

    case_constants = {
        "nom": MIANOWNIK,
        "gen": DOPEŁNIACZ,
        "dat": CELOWNIK,
        "acc": BIERNIK,
        "inst": NARZĘDNIK,
        "loc": MIEJSCOWNIK,
        "voc": WOŁACZ,
    }

    morfeusz = morfeusz2.Morfeusz(
        expand_tags=True,
        expand_dot=True,
        expand_underscore=True,
    )

    city_meta = {row["name"].lower(): row for row in cities}
    out: list[dict[str, str]] = []
    missing_nom: list[str] = []

    for lower_name in sorted(selected):
        meta = city_meta.get(lower_name)
        if meta is None:
            raise SystemExit(f"Priority city not found in TERYT city source: {lower_name}")
        name = meta["name"]
        generated: set[tuple[str, str]] = set()

        # TERYT/SIMC is the authoritative source for the nominative city surface.
        # Morfeusz/SGJP is used only to add attested non-nominative singular forms.
        generated.add(("nom", name))

        # Primary oracle: Morfeusz 2 / SGJP.
        for lemma_query in (name, lower_name):
            for orth, lemma, tag, _names, _labels in morfeusz.generate(lemma_query):
                if str(lemma).lower() != lower_name:
                    continue
                if not tag.startswith("subst:sg:"):
                    continue
                for case_tag in sorted(case_from_tag(tag)):
                    surface = str(orth).strip()
                    if not surface:
                        continue
                    surface = surface[:1].upper() + surface[1:]
                    generated.add((case_tag, surface))

        # Secondary oracle: data-only SGJP index. Reverse-validation prevents a
        # coincidental form from another lemma from entering the city layer.
        for case_tag, case_const in case_constants.items():
            if case_tag == "nom":
                continue
            try:
                variants = list(odmien_warianty(lower_name, case_const, POJEDYNCZA))
            except Exception:
                variants = []
            for variant in variants:
                form = str(variant).strip()
                if not form:
                    continue
                analyses = podaj(form, liczba=POJEDYNCZA)
                valid = any(
                    str(analysis.lemat).lower() == lower_name
                    and str(analysis.przypadek) == case_tag
                    and str(analysis.liczba) == "sg"
                    for analysis in analyses
                )
                if valid:
                    generated.add((case_tag, form[:1].upper() + form[1:]))

        for case_tag, surface in sorted(generated, key=lambda item: (CASES.index(item[0]), item[1])):
            out.append({
                "name": name,
                "gender": "",
                "layer": "city",
                "case": case_tag,
                "form": surface,
                "source": "Morfeusz 2 / SGJP generated from GUS TERYT SIMC city lemma",
                "morfeusz_version": str(morfeusz2.__version__),
            })

    # Nominative forms come directly from TERYT; therefore a city is valid even when
    # Morfeusz does not classify its proper-name lemma. Non-nominative forms remain
    # oracle-backed and are simply absent when SGJP has no analyzed form.

    with args.out_tsv.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["name", "gender", "layer", "case", "form", "source", "morfeusz_version"],
            delimiter="\t",
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(out)

    coverage = {}
    for row in out:
        coverage.setdefault(row["name"], set()).add(row["case"])

    report = {
        "oracle": "Morfeusz 2 / SGJP",
        "morfeusz_version": str(morfeusz2.__version__),
        "all_one_token_city_names": len(cities),
        "top_n": args.top_n,
        "priority_names": sorted(priorities),
        "selected_city_names": len(selected),
        "inflection_record_count": len(out),
        "case_counts": {
            case: sum(1 for row in out if row["case"] == case)
            for case in CASES
        },
        "names_with_non_nominative": sum(
            1 for cases in coverage.values() if len(cases) > 1
        ),
    }
    args.out_report.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
